### ISSUE TITLE
type_traits not found during compile

### ISSUE THREAD

**Issue by phodgers** [tommag/TMC5160_Arduino#1]
Hello,

I tried to compile the SPI example on Arduino 1.8.13 (Windows Install) but found an issue with type_traits not being found. I installed ArxTypeTraits from Arduino Library and referenced that in bitfield.h and it then compiled okay.

**Comment by tommag** [comment]
Thanks for reporting ! I should probably include ArxTypeTraits directly.

**Comment by matt-lamport** [comment]
I encountered the same issue when trying to compile the SPI example on Arduino 1.8.8 on Windows 10. All I had to do was change Line 11 in Bitfield.h from "#include <type_traits>" to "#include "type_traits.h" in order to get it to compile properly.

**Comment by tommag** [comment]
ArxTypeTraits is now a library dependency for Arduino and PlatformIO.
