### ISSUE TITLE
step dir pins

### ISSUE THREAD

**Issue by puredirect** [tommag/TMC5160_Arduino#10]
Hi! i have some problem, i tried it on a teensy 4.1 and does nothing, it holds the shaft strongly, if i try to turn it i can see changes on the serial out, should i wire the step and dir pins? you did not mention it in the project file

**Comment by tommag** [comment]
Hello, 
I don't see how I could give you any relevant advice if you don't at least give the name of the TMC5160 breakout board you're using and how you've wired everything ;)
Cheers,

**Comment by puredirect** [comment]
Hi! It solved, i had a 3d printer version one. The sd mode was soldered to vcc under the chip…. So it is stepdir only, my bob version come today tomorrow will try it. Thank you for the driver!

Az iPhone-omról küldve

**Comment by tommag** [comment]
Happy to know that you found the issue :)
