### ISSUE TITLE
Can only use default CS pin on Teensy 4.0

### ISSUE THREAD

**Issue by lukemm1979** [tommag/TMC5160_Arduino#12]
Hi,

I'm trying to use your library to control multiple (5) TMC5160 BOBs with a Teensy 4.0. I hooked up one driver to the Teensy and used the standard pins starting with your TMC5160 SPI example code, and changed the CS pin to 10. This works fine. However if I change the CS pin to any other GPIO (and the physical connection to match, of course), it doesn't work. 

I'm not sure if this is a Teensy problem or an issue with the library. Reading around it looks like the SPI peripheral on the Teensy may be restricted to pin 10, but this seems very strange to me so perhaps I've misunderstood. Could I use a software SPI library instead? 

Any help is greatly appreciated.

Luke

**Comment by lukemm1979** [comment]
This turned out to be an issue with a mislabelled silk screen - I've since been able to use the driver with multiple tmc5160s without issue.

**Comment by puredirect** [comment]
Hi Lukemm1979!
May i ask your code? I would like to initialize 3 of them?
I dont see any example on the internet!
***@***.***
THX!
Vendel

lukemm1979 ***@***.***> ezt írta (időpont: 2022. ápr. 6.,
Sze, 12:31):
