### ISSUE TITLE
Delay between SPI transfers is too short

### ISSUE THREAD

**Issue by DeanIsMe** [tommag/TMC5160_Arduino#15]
In `TMC5160_SPI::readRegister`, a delay is added between the 2 transfers with nop statements.
```
#define nop() asm volatile("nop")
nop();
nop();
nop();
```
On Teensy4 @ 600 MHz 3 system clocks is only 6 ns.
The TMC5160 datasheet has "CSN high time" minimum of 2*tCLK+10 ns, which is about 176 ns for the 12 MHz internal clock.
Hence the 'nop' delay is not compliant with the CSN high time.

**Impacts of this:**
In the _second_ transfer, if you read the SPI_STATUS register like this:
`spiStatus = _spi->transfer(address);` 
You'll see that the `spiStatus` is erratic and inconsistent. Increasing the delay between the transfers fixes this.

**Comment by tommag** [comment]
Indeed. 
I see that Teensy defines a _delayNanoseconds()_ function that would be useful : https://www.pjrc.com/teensy/td_timing_delay.html#delayMicroseconds but I don't know of a nice cross-platform way of handling such a short delay, do you have an idea ?

**Comment by DeanIsMe** [comment]
Check out #21. It should solve the problem in a cross-platform manner.

**Comment by tommag** [comment]
Thank you ! Before merging this one I want to take some time to test it out on different platforms. 
Also, it looks like it could be useful to have this code in a small, separate lib, it may be useful for other use cases. Do you mind if I package it in another lib ?

**Comment by DeanIsMe** [comment]
That makes sense.
No problem - you may package it in another lib.

**Comment by tommag** [comment]
I pushed some commits that should solve your issue but I don't have a Teensy 4 to test. I've tested it with a Teensy 3.5 and it seems to work but there was already a 1us delay between SPI transactions without additional delay. 

Cheers and thanks for reporting !
