### ISSUE TITLE
Using wrong default SPI mode

### ISSUE THREAD

**Issue by DeanIsMe** [tommag/TMC5160_Arduino#16]
This library uses SPI_MODE_0 by default, but Trinamic SPI interfaces use SPI_MODE_3.

I'm amazed that this library works so well when using the wrong SPI clock polarity and phase.

**Comment by tommag** [comment]
Thanks, looks like you're correct ! 
I've never really used SPI but mostly the UART connection and I think this code comes from the TMC5130 lib I forked in the beginning, maybe it explains why I've missed it all this time :)
Would you mind submitting a PR ? 
Thanks

**Comment by DeanIsMe** [comment]
Done! See PR #20
