### ISSUE TITLE
setTargetPosition at Velocity Mode

### ISSUE THREAD

**Issue by Cachago13** [tommag/TMC5160_Arduino#18]
Hi tommag,
i'm just struggling to use the setTargetPosition() function at Velocity Mode.
I tried to read the steps with getCurrentPosition() and stop the driver when the target position is achieved but that doesen't works.
When i tried to make 1 rotation then the stepper stops slight after one rotation.
How can i accuratly drive a distance? 
Thanks for the help.

**Comment by tommag** [comment]
Hello, 
As the name implies, "velocity mode" is used to drive the motor with a specified velocity. 
If you need to control the position / distance of a motor, then "positioning mode" is better suited !
