### ISSUE TITLE
Max Speed

### ISSUE THREAD

**Issue by Cachago13** [tommag/TMC5160_Arduino#22]
Hi,
it's not directly a driver problem i think.
I have a NEMA14 stepper and i can't go higher than 850 with the speed (acceleration is 1000).
Do you have some Know How about this?
Is it possible to go much higher? Is it a stepper problem or a software adjustment?

**Comment by tommag** [comment]
Hello, 

Can you be more precise with your issue ? What do you mean by "can't go higher than 850" ? Do you ask the driver to go faster and it doesn't or does the motor stall physically ? 

If the motor stalls (and you drive it with its specified current of course), then it's underpowered for your application and the only thing you can do is switch to a more powerful one.

**Comment by Cachago13** [comment]
Hello,

first, sorry for my bad explanation :)
I've a 17hs2408 Stepper motor.
<img width="582" alt="image" src="https://user-images.githubusercontent.com/110819027/216608949-640383d5-8c8f-4e0f-887c-d28700601f85.png">

At the moment i'm not able to go higher than 850 steps per second --> slightly more than 4 rounds per secon.
Is this just because of the physical properties from my motor or should it be possible to go higher?
Over 850 steps per second the motor just vibrates.

Thanks for your help!

**Comment by tommag** [comment]
In my experience most motors, when they are correctly sized for the load, can run at up to 1000 RPM (ie 3333 steps/s). 
So in your case it's probably that the motor is too weak for the load you're trying to move. 

Or if there is no load connected to the motor, maybe it needs some inertia on the axle, you can try adding a balanced weight to the motor shaft.

**Comment by tommag** [comment]
I'm closing this issue because it's unrelated to the TMC5160 library.
