### ISSUE TITLE
Set target function

### ISSUE THREAD

**Issue by simonedallai** [tommag/TMC5160_Arduino#31]
Hi, I would like to use the set target function in reference not to the position of the steps but in relation to the encoder, how can I do it?

**Comment by tommag** [comment]
I'm not sure I understand what you want to do, but you should be able to achieve what you want using `getEncoderPosition()` and `getCurrentPosition()`? 

There is no builtin closed loop management inside the TMC5160. You have to handle it yourself.

**Comment by simonedallai** [comment]
ok if I haven't misunderstood the set target function is only in relation
to the microsteps, if I want a closed loop I have to check the position of
the encoder at all times......

Il mar 19 mar 2024, 19:15 Tom Magnier ***@***.***> ha scritto:

**Comment by tommag** [comment]
Exactly. TMC4361 has built-in closed loop support but not TMC5160.

**Comment by simonedallai** [comment]
but in the 4361 library you made, a 5160 could fit, can the two go together?

Il mer 20 mar 2024, 12:36 Tom Magnier ***@***.***> ha scritto:
