### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by buddy-brakel** [tommag/TMC5160_Arduino#4]
Getting an error when compiling TMC5160 Config Wizard.

line 404: TMC5160::MotorParameters motorParams = {32, 0, 0};

ERROR: Could not convert '{32, 0, 0}' from 'braced-enclosed initializer list' to 'TMC5160::MotorParameters'

Arduino IDE version 1.9.0-beta.

**Comment by tommag** [comment]
Thanks for reporting!
Which board/architecture are you compiling for?

**Comment by buddy-brakel** [comment]
ESP32 Dev Module

**Comment by tommag** [comment]
Fixed in https://github.com/tommag/TMC5160_Arduino/commit/fbe2917ffaa95e27a39ff2f14acf3551ce84a725.
