### ISSUE TITLE
SPI for ESP

### ISSUE THREAD

**Issue by jblatcher** [tommag/TMC5160_Arduino#6]
Can the SPI be set up for the esp? Trying to run it over the hspi is this possible?

**Comment by tommag** [comment]
I guess it should work... Check out here for an example of setting up HSPI : https://github.com/espressif/arduino-esp32/blob/master/libraries/SPI/examples/SPI_Multiple_Buses/SPI_Multiple_Buses.ino 

Then the TMC5160_SPI constructor last argument lets you specify which SPI instance you want to use. 

I imagine that you would set it up like this ( /!\ I haven't tested this, this is just an example).

    SPIClass SPI_HSPI(HSPI);
    TMC5160_SPI motor(CS_PIN, TMC5160::DEFAULT_F_CLK, SPISettings(1000000, MSBFIRST, SPI_MODE0), SPI_HSPI);
